services:
  - type: web
    name: fintrack-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        sync: false  # Render will let you generate it manually

      # Database Configuration (PostgreSQL)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d40rq2mmcj7s73ep9rf0-a.virginia-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: fintrack_3fzq
      - key: DB_USERNAME
        value: fintrack1
      - key: DB_PASSWORD
        value: Q2ZASbo3J2c2oHwq8sgCeNMXbsOOjB6F

      # URL (important for Laravel)
      - key: APP_URL
        value: https://fintrack-api.onrender.com

      # Make sure Laravel runs correctly on Render
      - key: PORT
        value: 10000
